# Generated by Django 2.2.10 on 2020-04-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_bill_num_split'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='balance',
        ),
        migrations.AddField(
            model_name='bill',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='bill',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
